LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

PREBUILT_SHARED_LIBRARY := -L/home/reza/Qt/5.15.2/android/lib/ -lQt5Quick -lQt5Gui -lQt5QmlModels -lQt5Qml -lQt5Network -lQt5Core
LOCAL_SHARED_LIBRARIES := gstreamer_android

ifndef GSTREAMER_ROOT
ifndef GSTREAMER_ROOT_ANDROID
$(error GSTREAMER_ROOT_ANDROID is not defined!)
endif
GSTREAMER_ROOT            := $(GSTREAMER_ROOT_ANDROID)
endif

GSTREAMER_NDK_BUILD_PATH  := $(GSTREAMER_ROOT)/share/gst-android/ndk-build
include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS         := $(GSTREAMER_PLUGINS_CORE) $(GSTREAMER_PLUGINS_SYS) $(GSTREAMER_PLUGINS_PLAYBACK) $(GSTREAMER_PLUGINS_CODECS) $(GSTREAMER_PLUGINS_NET) $(GSTREAMER_PLUGINS_QT5)
GSTREAMER_EXTRA_LIBS      := -liconv
GSTREAMER_EXTRA_DEPS      := gstreamer-video-1.0
include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk
